---
all:
  hosts:
    node-1:
      ansible_host: node-1.local
    node-2:
      ansible_host: node-2.local
    node-3:
      ansible_host: node-3.local
    node-4:
      ansible_host: node-4.local
    node-5:
      ansible_host: node-5.local
    node-6:
      ansible_host: node-6.local
  children:
    swarm_managers:
      hosts:
        node-1:
        node-2:
        node-3:
    swarm_workers:
      hosts:
        node-4:
        node-5:
        node-6:
    swarm_nodes:
      children:
        swarm_managers:
        swarm_workers:
